version = 0.1

[default.global.parameters]
stack_name = "post-processing-wFFmpeg-service"
region = "us-west-2"

[default.deploy.parameters]
profile = "bstream"
resolve_s3 = true
s3_prefix = "post-processing-wFFmpeg-service"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DestinationBucket=\"serverlessflix-basecore-cdnstack-p6b-originbucket-qf6cyql0kb4m\" SourceBucket=\"serverlessflix-ivs-video-archive-1\" ServerlessFlixVideosTable=\"serverlessFlix-Video-table\" ServerlessFlixChannelsTable=\"serverlessFlix-channels-table\" cdnUrl=\"d3ih6h9pkrghoj.cloudfront.net\""


[prod.deploy.parameters]
stack_name = "post-processing-wFFmpeg-service"
resolve_s3 = true
s3_prefix = "post-processing-wFFmpeg-service"
region = "us-west-2"
profile= "stream"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DestinationBucket=\"serverlessflix-basecore-cdnstack-1nj-originbucket-vufxhay1e3cf\" SourceBucket=\"serverlessflix-ivs-video-archive\" ServerlessFlixVideosTable=\"serverlessFlix-Video-table\" ServerlessFlixChannelsTable=\"serverlessFlix-channels-table\" cdnUrl=\"dmpdx8pmqxo3f.cloudfront.net\""


[gitHub.deploy.parameters]
stack_name = "post-processing-wFFmpeg-service"
resolve_s3 = true
s3_prefix = "post-processing-wFFmpeg-service"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DestinationBucket=\"serverlessflix-basecore-cdnstack-1nj-originbucket-vufxhay1e3cf\" SourceBucket=\"serverlessflix-ivs-video-archive\" ServerlessFlixVideosTable=\"serverlessFlix-Video-table\" ServerlessFlixChannelsTable=\"serverlessFlix-channels-table\" cdnUrl=\"dmpdx8pmqxo3f.cloudfront.net\""