AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  serverlessVideo-plugin-manager

  Sample SAM Template for serverlessVideo-plugin-manager

Resources:
  PluginLifecycleWorkflow:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Events:
        EBRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "serverlessVideo.videoManager"
              detail-type:
                    - "recording-ready"
      Name:
        !Join [
          '',
          [
            !Ref 'AWS::AccountId',
            '-',
            !Ref 'AWS::Region',
            '-PluginLifecycleWorkflow',
          ],
        ]
      DefinitionUri: statemachine/workflow.asl.json
      DefinitionSubstitutions:
        DDBTable: !Ref serverlessVideoPluginHooksTable
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - StepFunctionsExecutionPolicy:
            StateMachineName:  
              !Join [
                '',
                [
                  !Ref 'AWS::AccountId',
                  '-',
                  !Ref 'AWS::Region',
                  '-PluginLifecycleWorkflow',
                ],
              ]
        - DynamoDBReadPolicy:
            TableName: !Ref serverlessVideoPluginHooksTable
        - EventBridgePutEventsPolicy:
            EventBusName: "default"
        - CloudWatchPutMetricPolicy: {}

        
  PluginTaskSuccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 3
      Environment:
        Variables:
          PluginLifecycleWorkflow: !Ref PluginLifecycleWorkflow
      Policies:
        - Statement:
            - Effect: Allow
              Resource: !Ref PluginLifecycleWorkflow
              Action:
                - states:sendTaskSuccess
      Events:
        pluginSuccess:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - prefix: serverlessVideo.plugin
              detail-type:
                - prefix: plugin-complete



  serverlessVideoPluginHooksTable:
    Type: AWS::DynamoDB::Table # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      TableName: serverlessVideoPluginHooksTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
