version = 0.1

[default.global.parameters]
stack_name = "ServerlessFlix-publisher-service"
region = "us-west-2"

[default.deploy.parameters]
stack_name = "ServerlessFlix-publisher-service"
region = "us-west-2"
resolve_s3 = true
s3_prefix = "ServerlessFlix-publisher-service"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "IoTRealtimeParameter=\"a2y72b1ntmnz5b-ats.iot.us-west-2.amazonaws.com\""
profile = "bstream"

[prod.deploy.parameters]
stack_name = "ServerlessFlix-publisher-service"
resolve_s3 = true
s3_prefix = "ServerlessFlix-publisher-service"
region = "us-west-2"
profile = "stream"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "IoTRealtimeParameter=\"a1cehcdh37vuqi.iot.us-west-2.amazonaws.com\""


[gitHub.deploy.parameters]
stack_name = "ServerlessFlix-publisher-service"
resolve_s3 = true
s3_prefix = "ServerlessFlix-publisher-service"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "IoTRealtimeParameter=\"a1cehcdh37vuqi.iot.us-west-2.amazonaws.com\""

