version = 0.1

[default.global.parameters]
stack_name = "serverlessFlix-BaseCore"
region = "us-west-2"


[default.deploy.parameters]
profile = "bstream"
resolve_s3 = true
s3_prefix = "serverlessFlix-BaseCore"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
confirm_changeset = true
parameter_overrides = "API=\"6az7efgnm3.execute-api.us-west-2.amazonaws.com\"  AuthDomainName=\"svideo-dev\""

[prod.global.parameters]
stack_name = "serverlessFlix-BaseCore"
profile = "stream"
region = "us-west-2"

[prod.deploy.parameters]
resolve_s3 = true
s3_prefix = "serverlessFlix-BaseCore"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
confirm_changeset = true
parameter_overrides = "API=\"cehu8ctixi.execute-api.us-west-2.amazonaws.com\" AuthDomainName=\"svideo\""

[gitHub.deploy.parameters]
stack_name = "serverlessFlix-BaseCore"
resolve_s3 = true
region = "us-west-2"
s3_prefix = "serverlessFlix-BaseCore"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
confirm_changeset = true
parameter_overrides = "API=\"cehu8ctixi.execute-api.us-west-2.amazonaws.com\" AuthDomainName=\"svideo\""


