version = 0.1

[default.global.parameters]
stack_name = "serverlessFlix-video-service"
region = "us-west-2"



[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "serverlessFlix-video-service"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "bstream"


[prod.deploy.parameters]
stack_name = "serverlessFlix-video-service"
resolve_s3 = true
s3_prefix = "serverlessFlix-video-service"
region = "us-west-2"
profile ="stream"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true


[gitHub.deploy.parameters]
stack_name = "serverlessFlix-video-service"
resolve_s3 = true
s3_prefix = "serverlessFlix-video-service"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true